# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.S1_wls <- function(summary, n) {
    .Call(`_metaBLUEX_S1_wls`, summary, n)
}

.S2_wls <- function(summary, n) {
    .Call(`_metaBLUEX_S2_wls`, summary, n)
}

.S3_wls <- function(summary, n) {
    .Call(`_metaBLUEX_S3_wls`, summary, n)
}

.S1_yang <- function(summary, n) {
    .Call(`_metaBLUEX_S1_yang`, summary, n)
}

.S2_yang <- function(summary, n) {
    .Call(`_metaBLUEX_S2_yang`, summary, n)
}

.S3_yang <- function(summary, n) {
    .Call(`_metaBLUEX_S3_yang`, summary, n)
}

.tertiles_yang <- function(summary, n) {
    .Call(`_metaBLUEX_tertiles_yang`, summary, n)
}

.quintiles_yang <- function(summary, n) {
    .Call(`_metaBLUEX_quintiles_yang`, summary, n)
}

.deciles_yang <- function(summary, n) {
    .Call(`_metaBLUEX_deciles_yang`, summary, n)
}

.S1_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S1_yang_logit`, summary, n)
}

.S2_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S2_yang_logit`, summary, n)
}

.S3_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S3_yang_logit`, summary, n)
}

.tertiles_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_tertiles_yang_logit`, summary, n)
}

.quintiles_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_quintiles_yang_logit`, summary, n)
}

.deciles_yang_logit <- function(summary, n) {
    .Call(`_metaBLUEX_deciles_yang_logit`, summary, n)
}

.S1_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S1_yang_lap`, summary, n)
}

.S2_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S2_yang_lap`, summary, n)
}

.S3_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S3_yang_lap`, summary, n)
}

.tertiles_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_tertiles_yang_lap`, summary, n)
}

.quintiles_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_quintiles_yang_lap`, summary, n)
}

.deciles_yang_lap <- function(summary, n) {
    .Call(`_metaBLUEX_deciles_yang_lap`, summary, n)
}

.S1_bala <- function(summary, n) {
    .Call(`_metaBLUEX_S1_bala`, summary, n)
}

.S2_bala <- function(summary, n) {
    .Call(`_metaBLUEX_S2_bala`, summary, n)
}

.S3_bala <- function(summary, n) {
    .Call(`_metaBLUEX_S3_bala`, summary, n)
}

.tertiles_bala <- function(summary, n) {
    .Call(`_metaBLUEX_tertiles_bala`, summary, n)
}

.quintiles_bala <- function(summary, n) {
    .Call(`_metaBLUEX_quintiles_bala`, summary, n)
}

.deciles_bala <- function(summary, n) {
    .Call(`_metaBLUEX_deciles_bala`, summary, n)
}

.S1_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S1_lap`, summary, n)
}

.S2_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S2_lap`, summary, n)
}

.S3_lap <- function(summary, n) {
    .Call(`_metaBLUEX_S3_lap`, summary, n)
}

.S1_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S1_logit`, summary, n)
}

.S2_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S2_logit`, summary, n)
}

.S3_logit <- function(summary, n) {
    .Call(`_metaBLUEX_S3_logit`, summary, n)
}

